sonar.projectKey=rcpc265_sales-orders-api
sonar.organization=rcpc265

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=sales-orders-api
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=app,config,database,routes
sonar.tests=tests
sonar.php.coverage.reportPaths=build/logs/clover.xml
sonar.php.tests.reportPath=build/logs/junit.xml

# Exclusions
sonar.exclusions=vendor/**,public/**,resources/**,storage/**,bootstrap/**,**/*.blade.php
